config/routes.rb
Rails.application.routes.draw do
  get 'checkout/index'
  get 'checkout/create'
  get 'carts/show'

  get 'checkout/address', to: 'checkout#address'
  post 'checkout/create_address', to: 'checkout#create_address'
  patch 'checkout/update_address/:id', to: 'checkout#update_address', as: 'update_address'
  get 'checkout/invoice', to: 'checkout#invoice' # Add this line to handle the invoice view
  post 'checkout/pay_now', to: 'checkout#pay_now', as: 'pay_now_checkout'


  resources :guest_checkout, only: [] do
    collection do
      get 'new_address'
      post 'create_address', as: 'create_address'
      get 'invoice', to: 'guest_checkout#invoice', as: 'invoice' # <-- Fixed this line
    end
  end


  root 'application#choose_root_path' # Change the root route to point to choose_root_path

  resources :products, only: [:index, :show] do
    member do
      get :view_in_3d
    end
  end

  resources :categories, only: [:show]
  resource :cart, only: [:show] do
    post 'add_item'
    post 'remove_item'
    post 'update_item'
  end

  get 'about_pages/show'
  get 'user_dashboard', to: 'users#dashboard', as: 'user_dashboard'

  get 'contact_pages/show'
  resources :addresses, only: [:index, :new, :create, :edit, :update, :destroy]




  devise_for :users, path: 'users', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'signup' }
  # Active Admin routes for admin users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # Other routes for your application can be added here.
  get '/contact', to: 'contact_pages#show'
  get '/about', to: 'about_pages#show'
  get 'checkout', to: 'checkout#index'
  post 'checkout', to: 'checkout#create'

  resources :users, only: [:show]

  # Add the custom route for users#index
  get 'users', to: 'users#index', as: 'users'
end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController
  before_action :ensure_cart_is_not_empty, only: [:getcheckout, :invoice]
  before_action :set_address, only: [:update_address]

  def getcheckout
    if session[:province_id].blank?
      flash[:alert] = "Province information is missing!"
      redirect_to checkout_address_path # Redirect to the appropriate path
      return
    end
    @province_id = params[:province_id] || (user_signed_in? ? current_user.province_id : nil)

    unless @province_id
      flash[:alert] = "Province information is missing!"
      redirect_to checkout_address_path # Redirect to the appropriate path
      return
    end

    puts "Province ID: #{@province_id}"
    # Find the province of the user or use the one provided in params


    if session[:province_id].blank?
      flash[:alert] = "Province information is missing!"
      redirect_to checkout_address_path # Redirect to the appropriate path
      return
    end
    # Calculate the total price of the cart
    @total = @cart.sum { |item| Product.find(item['id']).price * item['quantity'].to_i }

    # Get tax details of the province
    @province = Province.find(@province_id)
    @pst = (@total * @province.pst) / 100
    @gst = (@total * @province.gst) / 100
    @hst = (@total * @province.hst) / 100
    @tax = @pst + @gst + @hst
    @final_total = @total + @tax


    session[:total] = @total
    session[:province_id] = @province_id
    session[:pst] = @pst
    session[:gst] = @gst
    session[:hst] = @hst
    session[:tax] = @tax

    redirect_to checkout_path
  end

  def invoice
    if session[:province_id].blank?
      flash[:alert] = "Province information is missing!"
      redirect_to checkout_address_path # Redirect to the appropriate path
      return
    end
    if user_signed_in?
      @address = Address.find_by(user_id: current_user.id)
    end
    # Get the cart items
    @cart_items = session[:cart] || []
    puts "session[:cart]: #{session[:cart].inspect}"

    # Calculate the total, tax, and other details
    @total = @cart_items.sum do |id, quantity|
      product = Product.find(id)
      product.price * quantity.to_i
    end

    @province = Province.find(session[:province_id])
    @pst = (@total * @province.pst) / 100
    @gst = (@total * @province.gst) / 100
    @hst = (@total * @province.hst) / 100
    @tax = @pst + @gst + @hst

    @cart = @cart_items.map do |id, quantity|
      puts "item id: #{id}, quantity: #{quantity}"
      product = Product.find(id)
      { product: product, quantity: quantity.to_i, price: product.price * quantity.to_i }
    end

  end

  def pay_now
    ActiveRecord::Base.transaction do
      user = current_user

      address = Address.find_by(user_id: user.id)

      total = params[:total].to_f
      tax = params[:tax].to_f

      order = Order.create!(total: total + tax, user: user, address: address, status: "new")

      customer_name = user.name || "Default Customer Name"
      customer = Customer.create!(
        name: customer_name,
        email: user.email,
        user_id: user.id,
        order_id: order.id,
        subtotal: total,
        gst: params[:gst],
        pst: params[:pst],
        hst: params[:hst],
        total_with_taxes: total + tax,
        product_data: params[:cart]
      )

      cart_items = JSON.parse(params[:cart])
      cart_items.each do |item_data|
        product = Product.find(item_data["product"]["id"])
        OrderItem.create!(order: order, product: product, quantity: item_data["quantity"].to_i)
      end
    end

    # Redirect to a success page or whatever you want to do next
  rescue => e
    flash[:alert] = "An error occurred while processing the order: #{e.message}"
    redirect_to checkout_path
  end


  def address
    if user_signed_in?
      @address = Address.find_by(user_id: current_user.id) || Address.new
    else
      # Handle the case for users who are not signed in
    end
  end

  def create_address
    @address = Address.new(address_params)
    if @address.save
      session[:province_id] = @address.province_id # Set the province_id in the session
      flash[:notice] = 'Address saved successfully!'
      redirect_to checkout_invoice_path # or wherever you want to redirect
    else
      flash[:alert] = 'Unable to save address!'
      render :address
    end
  end

  def update_address
    if @address.update(address_params)
      session[:province_id] = @address.province_id # Set the province_id in the session
      flash[:notice] = 'Address updated successfully!'
      redirect_to checkout_invoice_path# or wherever you want to redirect
    else
      flash[:alert] = 'Unable to update address!'
      render :address
    end
  end

  private

  def ensure_cart_is_not_empty
    @cart = session[:cart] || []
    redirect_to cart_path if @cart.empty?
  end
  def set_address
    @address = Address.find(params[:id])
  end

  def address_params
    params.require(:address).permit(:street, :city, :province_id, :user_id)
  end
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/views/checkout/_form.html.erb
<%= f.label :street %>
<%= f.text_field :street %><br>

<%= f.label :city %>
<%= f.text_field :city %><br>

<%= f.label :province %>
<%= f.collection_select :province_id, Province.all, :id, :name %><br>


<%= f.hidden_field :user_id, value: current_user&.id if user_signed_in? %>

app/views/checkout/address.html.erb
<div class="address-container">
  <% if user_signed_in? && @address.persisted? %>
    <%= form_for @address, url: update_address_path(@address), method: :patch do |f| %>
      <h1>Edit Address</h1>
      <%= render 'form', f: f %>
      <%= f.submit "Update" %>
    <% end %>
  <% else %>
    <%= form_for @address, url: { action: 'create_address' }, method: :post do |f| %>
      <h1>Add Address</h1>
      <%= render 'form', f: f %>
      <%= f.submit "Save" %>
    <% end %>
  <% end %>
  <%= link_to 'Proceed to Invoice', checkout_invoice_path(province_id: @address.province_id), class: 'invoice-button' %>
</div>

app/views/checkout/get_checkout.html.erb
<%= form_with url: create_address_guest_checkout_index_path, method: :post, local: true do |form| %>
  <% address_fields = { street: nil, city: nil, province_id: nil } %>
  <%= form.fields_for :address, OpenStruct.new(address_fields) do |a| %>
    <%= a.text_field :street, placeholder: 'Street' %>
    <%= a.text_field :city, placeholder: 'City' %>
    <%= a.select :province_id, Province.all.collect { |p| [p.name, p.id] } %>
  <% end %>
  <%= form.submit "Continue to Payment" %>
<% end %>

app/views/checkout/invoice.html.erb
 <%= form_with url: pay_now_checkout_path, method: :post do %>
 <div class="invoice-page">
    <h1>Invoice</h1>
    <h3>From</h3>
    <h5>Canadian Agri Tech</h5>
    <h6>2915 Pembina hwy</h6>
    <h6>R3c 1Y9</h6>
    <h6>204 888 2822</h6>
    <h3>To</h3>
    <% if user_signed_in? %>

        <h6>Name: <%= current_user.name %></h6>
        <h6> Email: <%= current_user.email %></h6>
      <% elsif current_user.name.present? %>
        <h6>Name: <%= current_user.name %></h6>
      <% elsif current_user.email.present? %>
        <h6>Email: <%= current_user.email %></h6>
      <% end %>


    <h5><%= @address.street %></h5>
    <h6><%= @address.city %>, <%= @address.province.name %></h6>

    <table>
      <thead>
        <tr>
          <th>Product</th>
          <th>Quantity</th>
          <th>Price</th>
        </tr>
      </thead>
      <tbody>
        <% @cart.each do |item| %>
          <tr>
            <td><%= item[:product].name %></td>
            <td><%= item[:quantity] %></td>
            <td><%= number_to_currency(item[:price]) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <h2>Summary</h2>
    <p>PST: <%= number_to_currency(@pst) %></p>
    <p>GST: <%= number_to_currency(@gst) %></p>
    <p>HST: <%= number_to_currency(@hst) %></p>
    <p>Total: <%= number_to_currency(@total + @tax) %></p>
     <%= hidden_field_tag :total, @total %>
  <%= hidden_field_tag :pst, @pst %>
  <%= hidden_field_tag :gst, @gst %>
  <%= hidden_field_tag :hst, @hst %>
  <%= hidden_field_tag :tax, @tax %>
  <%= hidden_field_tag :province_id, @address.province_id %>
  <%= hidden_field_tag :cart, @cart.to_json %>

  <%= submit_tag 'Pay Now', class: 'invoice-button' %>

  </div>
  <% end %>