config/routes.rb
Rails.application.routes.draw do
  get 'checkout/index'
  get 'checkout/create'
  get 'carts/show'

  get 'checkout/address', to: 'checkout#address'
  post 'checkout/create_address', to: 'checkout#create_address'
  patch 'checkout/update_address/:id', to: 'checkout#update_address', as: 'update_address'
  get 'checkout/invoice', to: 'checkout#invoice' # Add this line to handle the invoice view
  post 'checkout/pay_now', to: 'checkout#pay_now', as: 'pay_now_checkout'


  resources :guest_checkout, only: [] do
    collection do
      get 'new_address'
      post 'create_address', as: 'create_address'
      get 'invoice', to: 'guest_checkout#invoice', as: 'invoice' # <-- Fixed this line
    end
  end


  root 'application#choose_root_path' # Change the root route to point to choose_root_path

  resources :products, only: [:index, :show] do
    member do
      get :view_in_3d
    end
  end

  resources :categories, only: [:show]
  resource :cart, only: [:show] do
    post 'add_item'
    post 'remove_item'
    post 'update_item'
  end

  get 'about_pages/show'
  get 'user_dashboard', to: 'users#dashboard', as: 'user_dashboard'

  get 'contact_pages/show'
  resources :addresses, only: [:index, :new, :create, :edit, :update, :destroy]




  devise_for :users, path: 'users', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'signup' }
  # Active Admin routes for admin users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # Other routes for your application can be added here.
  get '/contact', to: 'contact_pages#show'
  get '/about', to: 'about_pages#show'
  get 'checkout', to: 'checkout#index'
  post 'checkout', to: 'checkout#create'

  resources :users, only: [:show]

  # Add the custom route for users#index
  get 'users', to: 'users#index', as: 'users'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :addresses
         has_many :card_details
         has_many :orders
  has_one :customer
  def self.ransackable_attributes(auth_object = nil)
    ["admin", "created_at", "email", "encrypted_password", "id", "name", "remember_created_at", "reset_password_sent_at", "reset_password_token", "updated_at"]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = current_user
  end
  def dashboard
    # Add any necessary logic here
  end
end

app/views/users/dashboard.html.erb
<div class="jumbotron text-center">
  <h1>Welcome to Canadian Agri Tech</h1>
  <p class="para">Your Partner in Agricultural Innovation</p>
</div>

<div class="container content-section">
  <h2>About Canadian Agri Tech</h2>
  <p>We at Canadian Agri Tech are committed to advancing the field of agriculture through innovation and technology. Our cutting-edge solutions empower farmers to achieve more with less, maximizing efficiency and sustainability.</p>

  <h2>Our Values</h2>
  <p>Integrity, Innovation, Excellence, Sustainability, Community</p>

  <h2>Contact Us</h2>
  <p>Email: info@canadianagritech.com</p>
  <p>Phone: 123-456-7890</p>
</div>

app/views/users/index.html.erb
<p>Please Login</p>

app/views/users/show.html.erb
<div class="user-profile">
  <h1>User Profile</h1>

  <p><strong>Email:</strong> <%= @user.email %></p>
  <% if user_signed_in? %>
    <h2>Your Addresses</h2>

    <% @user.addresses.each do |address| %>
      <div>
        <p><%= address.street %>, <%= address.city %>, <%= address.province.name %></p>
        <%= link_to 'Edit', edit_address_path(address) %>
        <%= button_to 'Delete', address_path(address), method: :delete, data: { confirm: 'Are you sure?' }, class: 'button-to' %>
      </div>
    <% end %>

    <%= link_to 'Add New Address', new_address_path, class: 'button-to' %>
  <% end %>
</div>