config/routes.rb
Rails.application.routes.draw do
  get 'checkout/index'
  get 'checkout/create'
  get 'carts/show'

  get 'checkout/address', to: 'checkout#address'
  post 'checkout/create_address', to: 'checkout#create_address'
  patch 'checkout/update_address/:id', to: 'checkout#update_address', as: 'update_address'
  get 'checkout/invoice', to: 'checkout#invoice' # Add this line to handle the invoice view
  post 'checkout/pay_now', to: 'checkout#pay_now', as: 'pay_now_checkout'


  resources :guest_checkout, only: [] do
    collection do
      get 'new_address'
      post 'create_address', as: 'create_address'
      get 'invoice', to: 'guest_checkout#invoice', as: 'invoice' # <-- Fixed this line
    end
  end


  root 'application#choose_root_path' # Change the root route to point to choose_root_path

  resources :products, only: [:index, :show] do
    member do
      get :view_in_3d
    end
  end

  resources :categories, only: [:show]
  resource :cart, only: [:show] do
    post 'add_item'
    post 'remove_item'
    post 'update_item'
  end

  get 'about_pages/show'
  get 'user_dashboard', to: 'users#dashboard', as: 'user_dashboard'

  get 'contact_pages/show'
  resources :addresses, only: [:index, :new, :create, :edit, :update, :destroy]




  devise_for :users, path: 'users', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'signup' }
  # Active Admin routes for admin users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # Other routes for your application can be added here.
  get '/contact', to: 'contact_pages#show'
  get '/about', to: 'about_pages#show'
  get 'checkout', to: 'checkout#index'
  post 'checkout', to: 'checkout#create'

  resources :users, only: [:show]

  # Add the custom route for users#index
  get 'users', to: 'users#index', as: 'users'
end

app/models/cart.rb
# cart.rb
class Cart
  attr_reader :items, :user

  def initialize(session, user)
    @session = session
    @user = user
    @session[:cart] ||= {}
    @items = @session[:cart]
  end

  def add_item(product_id, quantity = 1)
    product_id = product_id.to_s
    if @items[product_id]
      @items[product_id] += quantity
    else
      @items[product_id] = quantity
    end

    save_to_database
  end

  def remove_item(product_id)
    product_id = product_id.to_s
    @items.delete(product_id)
    save_to_database
  end

  def update_item(product_id, quantity)
    product_id = product_id.to_s
    @items[product_id] = quantity.to_i
    save_to_database
  end

  def total
    @items.sum { |product_id, quantity| product_total(Product.find_by(id: product_id), quantity) }
  end

  private

  def product_total(product, quantity)
    return 0 unless product

    product.price * BigDecimal(quantity)
  end

  private

  def save_to_database
    return unless @user

    shopping_cart = @user.shopping_cart || ShoppingCart.find_or_initialize_by(user: @user)
    shopping_cart.total_price = total

    shopping_cart.transaction do
      shopping_cart.save!

      shopping_cart.cart_items.destroy_all

      @items.each do |product_id, quantity|
        product = Product.find_by(id: product_id)
        if product
          cart_item = shopping_cart.cart_items.build(product: product, quantity: quantity)
          cart_item.cart_id = shopping_cart.id  # Set the cart_id here
          cart_item.save!
        end
      end
    end

    clear unless @user
  end

  def clear
    @session[:cart] = {}
    @items = @session[:cart]
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  include Breadcrumbable
  before_action :set_cart
  before_action :set_user
  before_action :set_product, only: [:show, :add_item]  # Updated

  def show
    product_ids = @cart.items.keys
    @products = Product.where(id: product_ids)
    @addresses = Address.all
  end

  def add_item
    @cart.add_item(params[:product_id].to_i, params[:quantity])

    flash[:notice] = 'Item added to cart successfully!'
    redirect_to cart_path(product_id: @product.id)  # Updated
  end

  def remove_item
    @cart.remove_item(params[:product_id])
    flash[:notice] = 'Item removed from cart successfully!'
    redirect_to cart_path
  end

  def update_item
    @cart.update_item(params[:product_id], params[:quantity])
    flash[:notice] = 'Cart updated successfully!'
    redirect_to cart_path
  end

  def total
    @items.sum { |product_id, quantity| Product.find(product_id).price * quantity.to_d }
  end


  private

  def set_cart
    @cart = Cart.new(session)
    if !current_user && session[:cache_cleared]
      @cart.clear_items
      session[:cache_cleared] = false
    end
  end


  def set_user
    @user = current_user || User.new
  end

  def set_product
    @product = Product.find(params[:product_id]) if params[:product_id].present?
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/show.html.erb
<div class="flash-notice">
  <% if flash[:notice].present? %>
    <%= flash[:notice] %>
  <% else %>
    Canadian Agri Tech
  <% end %>
</div>

<div class="cart-page">
  <h1>Your Cart</h1>
  <% if @products.any? %>
    <table class="table">
    <!-- Cart table code here -->
    <thead>
      <tr>
        <th>Name</th>
        <th>Price</th>
        <th>Quantity</th>
        <th>Total</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @products.each do |product| %>
        <tr>
          <td><%= product.name %></td>
          <td><%= product.price %></td>
          <td>
            <%= form_with(url: update_item_cart_path, method: :post) do |form| %>
              <%= form.hidden_field :product_id, value: product.id %>
              <%= form.number_field :quantity, value: @cart.items[product.id.to_s], min: 1 %>
              <%= form.submit 'Update' %>
            <% end %>
          </td>
          <td><%= product.price * BigDecimal(@cart.items[product.id.to_s]) %></td>

          <td>
            <%= form_with(url: remove_item_cart_path, method: :post) do |form| %>
              <%= form.hidden_field :product_id, value: product.id %>
              <%= form.submit 'Remove' %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <h2>Total: <%= @cart.total %></h2>




<% if user_signed_in? %>
  <%= button_to 'Proceed to Pay', checkout_address_path, method: :get, class: 'address-button' %>
<% else %>
<%= link_to 'Proceed as Guest', new_address_guest_checkout_index_path, class: 'address-button' %>

<% end %>


<% else %>
  <p>Your cart is empty. Please add products to the cart.</p>

<% end %>